version: "3"

services:
  # Database
  # -----------------------------------------
  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    volumes:
      - db_data:/var/lib/mysql
      - ./db-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  # WordPress
  # -----------------------------------------
  wordpress:
    image: wordpress:php7.4-apache
    user: root
    container_name: ${PROJECT_NAME}-web
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
    ports:
      - ${PORT_NUM}:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    domainname: ${PROJECT_NAME}.test

  # phpMyAdmin
  # -----------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:3306
      - PMA_USER=${WORDPRESS_DB_USER}
      - PMA_PASSWORD=${WORDPRESS_DB_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db

volumes:
  db_data:
